"""fk_ondelete_set_null

Revision ID: 14ccf8d6cec6
Revises: ac2df596c696
Create Date: 2026-05-20 17:57:23.582843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ccf8d6cec6'
down_revision: Union[str, None] = 'ac2df596c696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledge_items_integration_id_fkey', 'knowledge_items', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_items', 'integrations', ['integration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_items', type_='foreignkey')
    op.create_foreign_key('knowledge_items_integration_id_fkey', 'knowledge_items', 'integrations', ['integration_id'], ['id'])
    # ### end Alembic commands ###
