"""add_integrations

Revision ID: ac2df596c696
Revises: 972b258a01e9
Create Date: 2026-05-20 17:24:59.726477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2df596c696'
down_revision: Union[str, None] = '972b258a01e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('SLACK', 'NOTION', 'LINEAR', name='integrationtype'), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('team_id', sa.String(length=255), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('bot_token', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.Enum('IDLE', 'SYNCING', 'ERROR', name='syncstatus'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'type', name='uq_integrations_org_type')
    )
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.add_column('knowledge_items', sa.Column('integration_id', sa.String(length=32), nullable=True))
    op.add_column('knowledge_items', sa.Column('external_id', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_knowledge_items_integration_id'), 'knowledge_items', ['integration_id'], unique=False)
    op.create_unique_constraint('uq_ki_integration_external', 'knowledge_items', ['integration_id', 'external_id'])
    op.create_foreign_key(None, 'knowledge_items', 'integrations', ['integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_items', type_='foreignkey')
    op.drop_constraint('uq_ki_integration_external', 'knowledge_items', type_='unique')
    op.drop_index(op.f('ix_knowledge_items_integration_id'), table_name='knowledge_items')
    op.drop_column('knowledge_items', 'external_id')
    op.drop_column('knowledge_items', 'integration_id')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
